import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity=0.8
[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 18

#for video
# size = 35.0

